POST http://localhost:8080/api/v1/company/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTg0OTYzOTksImV4cCI6MTY1ODQ5OTk5OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiOGE4YTg0OTY4MjI2MTVjZTAxODIyNjE2OWRhYTAwMDAifQ.ftre-ag0aq3SZ18FsfRYeCxApfWhr4EWZl1Mk5C-CZ8
Content-Type: application/json

{
  "name": "ibo bank2",
  "username": "bank2",
  "password": "123",
  "address": "chorsu2",
  "contact": "company2",
  "servicePercentage": 0.3,
  "role": "ROLE_BANK"
}

###
GET http://localhost:8080/init/initAdmin